import type { LocalePack } from "@12-apps/i18n";
const pt = {
  week: "Semana", next: "Próximo", viewWorkout: "Ver Treino", weekEnded: "Semana encerrada. Bom trabalho.",
  yourWorkouts: "Seus treinos", sessions: "Treinos", tonnes: "Toneladas", notPerformed: "Não realizado", lastLoad: "última kg",
  plannedTotal: "séries previstas", volumeEntryHint: "Ver séries previstas por grupo muscular", target: "meta", perSet: "por série", nextSet: "Próxima: série",
  decreaseLoad: "Diminuir 2,5 kg", increaseLoad: "Aumentar 2,5 kg", soundOn: "Ligar som", soundOff: "Desligar som",

  brand: "FUTURE GYM", clientRole: "Cliente", ownerRole: "Proprietário e cliente", sample: "DEMONSTRAÇÃO", sampleNotice: "Dados de exemplo nesta sessão. Sem conta, cobrança ou envio ao treinador.",
  provider: "Seu espaço", changeProvider: "Trocar espaço", chooseProvider: "Escolha seu espaço", providerHint: "Sua ficha e seu histórico ficam separados em cada espaço.",
  home: "Início", workouts: "Treinos", history: "Histórico", yourPlan: "Sua ficha", weekPlan: "Ficha da semana", today: "TREINO DE HOJE", restDay: "Dia de descanso", restHint: "Seu próximo treino está na ficha abaixo.",
  active: "TREINO EM ANDAMENTO", openWorkout: "Abrir treino", resume: "Voltar ao treino", startWorkout: "Iniciar treino", assigned: "Ficha do seu treinador", assignedHint: "A prescrição é de exemplo. Aqui você registra o que fez, sem alterar a ficha.",
  exercises: "Exercícios", sets: "séries", repetitions: "repetições", minutes: "min", weekProgress: "Treinos nesta semana", of: "de", rest: "Descanso", workout: "Treino", suggested: "sugestão kg", by: "Orientação", seconds: "s", interval: "intervalo", execution: "execução", total: "Total", set: "Série", loads: "Cargas e repetições", completed: "Concluída", completedSets: "Séries concluídas", pending: "Pendente", edit: "Editar", back: "Voltar", cancel: "Cancelar", save: "Salvar", kg: "Carga (kg)", reps: "Repetições", editSet: "Registrar série", invalidSet: "Use carga de 0 a 1.000 kg e 1 a 100 repetições inteiras. Carga aceita até duas casas decimais.",
  ready: "PRONTO", working: "EXECUÇÃO", resting: "INTERVALO", exerciseDone: "EXERCÍCIO CONCLUÍDO", paused: "PAUSADO", startSet: "Iniciar série", completeSet: "Série concluída", pause: "Pausar", continueTimer: "Retomar", moreRest: "+15 segundos", skipRest: "Pular intervalo", timerEnded: "Tempo encerrado. Confirme a série quando terminar.", timerHint: "O timer não marca séries sozinho. Só conta o que você confirmar.", nextExercise: "Próximo exercício", previousExercise: "Exercício anterior", finish: "Concluir treino", endSession: "Encerrar treino", finishTitle: "Encerrar treino?", finishHint: "Só as séries marcadas entram no histórico e na tonelagem.", saveFinish: "Salvar e encerrar", discard: "Descartar treino", keepTraining: "Continuar treinando", goHome: "Voltar à ficha", summary: "Treino concluído", recorded: "Cargas anotadas", duration: "Duração", volume: "kg total", noHistory: "Nenhum treino concluído ainda", noHistoryHint: "Quando você tocar em “Concluir treino”, ele aparece aqui com as cargas anotadas.", noSession: "Nenhum treino em andamento", noSessionHint: "Abra uma ficha para começar, ou volte ao espaço onde iniciou seu treino.", unavailable: "Treino indisponível neste espaço", unavailableHint: "Volte à ficha do espaço selecionado.", weeklyVolume: "Volume previsto", weeklyVolumeHint: "Séries diretas previstas por grupo. Leitura da ficha de exemplo, sem avaliação clínica ou faixa ideal.", inMemory: "Os registros de demonstração são apagados ao reiniciar o app.", days: ["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"],
};
const en: typeof pt = {
  week: "Week", next: "Next", viewWorkout: "View Workout", weekEnded: "Week complete. Well done.",
  yourWorkouts: "Your workouts", sessions: "Workouts", tonnes: "Tonnes", notPerformed: "Not performed", lastLoad: "last kg",
  plannedTotal: "planned sets", volumeEntryHint: "View planned sets per muscle group", target: "target", perSet: "per set", nextSet: "Next: set",
  decreaseLoad: "Decrease 2.5 kg", increaseLoad: "Increase 2.5 kg", soundOn: "Turn sound on", soundOff: "Turn sound off",

  brand: "FUTURE GYM", clientRole: "Client", ownerRole: "Owner and client", sample: "DEMO", sampleNotice: "Sample data for this session. No account, billing, or trainer transmission.", provider: "Your space", changeProvider: "Change space", chooseProvider: "Choose your space", providerHint: "Each space keeps its own plan and history.", home: "Home", workouts: "Workouts", history: "History", yourPlan: "Your plan", weekPlan: "Weekly plan", today: "TODAY'S WORKOUT", restDay: "Rest day", restHint: "Your next workout is in the plan below.", active: "WORKOUT IN PROGRESS", openWorkout: "Open workout", resume: "Resume workout", startWorkout: "Start workout", assigned: "Your trainer's plan", assignedHint: "This is a sample prescription. Record what you did without changing the plan.", exercises: "Exercises", sets: "sets", repetitions: "repetitions", minutes: "min", weekProgress: "Workouts this week", of: "of", rest: "Rest", workout: "Workout", suggested: "suggested kg", by: "Guidance", seconds: "s", interval: "rest", execution: "execution", total: "Total", set: "Set", loads: "Loads and repetitions", completed: "Completed", completedSets: "Completed sets", pending: "Pending", edit: "Edit", back: "Back", cancel: "Cancel", save: "Save", kg: "Load (kg)", reps: "Repetitions", editSet: "Record set", invalidSet: "Use 0–1,000 kg and 1–100 whole repetitions. Load accepts up to two decimal places.", ready: "READY", working: "EXECUTION", resting: "REST", exerciseDone: "EXERCISE COMPLETE", paused: "PAUSED", startSet: "Start set", completeSet: "Set completed", pause: "Pause", continueTimer: "Resume", moreRest: "+15 seconds", skipRest: "Skip rest", timerEnded: "Time is up. Confirm the set when you finish.", timerHint: "The timer never records sets automatically. Only your confirmations count.", nextExercise: "Next exercise", previousExercise: "Previous exercise", finish: "Finish workout", endSession: "End workout", finishTitle: "End workout?", finishHint: "Only completed sets count toward history and tonnage.", saveFinish: "Save and finish", discard: "Discard workout", keepTraining: "Keep training", goHome: "Back to plan", summary: "Workout completed", recorded: "Recorded loads", duration: "Duration", volume: "total kg", noHistory: "No completed workout yet", noHistoryHint: "When you tap “Finish workout”, it appears here with the recorded loads.", noSession: "No active workout", noSessionHint: "Open a plan to start, or return to the space where you started your workout.", unavailable: "Workout unavailable in this space", unavailableHint: "Return to the selected space's plan.", weeklyVolume: "Planned volume", weeklyVolumeHint: "Planned direct sets per muscle group. Sample plan information, not a clinical assessment or ideal range.", inMemory: "Demo records are cleared when the app restarts.", days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
};
export const CLIENT_COPY: LocalePack<typeof pt> = { "pt-BR": pt, "en-US": en };
export type ClientCopy = typeof pt;
export const formatNumber = (value: number) => value.toLocaleString("pt-BR", { maximumFractionDigits: 2 });
export const formatInputNumber = (value: number) => value.toLocaleString("pt-BR", { maximumFractionDigits: 2, useGrouping: false });
export const formatClock = (milliseconds: number) => {
  const seconds = Math.max(0, Math.ceil(milliseconds / 1000));
  return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, "0")}`;
};

export const formatDuration = (seconds: number, minutes = "min") => {
  const rounded = Math.round(seconds / 60);
  return rounded >= 60 ? `${Math.floor(rounded / 60)}h${String(rounded % 60).padStart(2, "0")}` : `${rounded} ${minutes}`;
};
